# ベースイメージを指定
FROM ruby:latest

# 作業ディレクトリを設定
WORKDIR /backend

ARG RUBYGEMS_VERSION=3.4.6

COPY Gemfile /backend/Gemfile

# Railsアプリの依存パッケージをインストール
COPY Gemfile Gemfile.lock ./
#RUN bundle install
RUN gem update --system ${RUBYGEMS_VERSION} && \
    bundle install

#RUN rails db:create
#RUN rails db:migrate

#データベースのバックアップ
COPY . /backend

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# ポートを公開
#EXPOSE 5000

# Railsサーバーを起動
CMD ["rails", "server", "-b", "0.0.0.0"]

